### ISSUE TITLE
Lab Report 2 Feedback 

### ISSUE THREAD

**Issue by mrkylesmith** [kyrafetter/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [] Symptom shown as command + output for bug/input 1
- Need to show command here
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [] Symptom shown as command + output for bug/input 2
- show command here
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [] Symptom shown as command + output for bug/input 3
- show command here
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
Great effort with your level of detail!  Please show the symptom as command + output (could be a screenshot).  Well done overall, good lab report. 

Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by kyrafetter** [comment]
Hi!

I have a quick question: I'm pretty sure that I already show the symptom as an output for each example. Is this correct? In that case, would the only thing that I need to add be the symptom as a command (ie. the javac and java commands that I ran in order to produce the shown symptom/output)? 

Thanks for the clarification!

**Comment by mrkylesmith** [comment]
Hi, yes that is correct, I see you added the commands used to produce the symptom/output. Well done, I have updated your score.
